### ISSUE TITLE
Better screenshot titles

### ISSUE THREAD

**Issue by benilovj** [design-history/design-history#191]
If the files have reasonable names, the default behaviour is fine:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/23801/217343716-972b95a5-41cb-4a4a-839c-8a777f478a26.png">

It'd be nicer to have cleaner names though:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/23801/217343771-7c704a0d-bc10-4b1a-9684-2f74baa2dc54.png">

Stretch goal: the screenshot title edit pre-populated by deslugifying the screenshot name?

**Comment by benilovj** [comment]
As per @tvararu's suggestion, I tried to work around this by removing dashes from my filenames:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/23801/217518895-47889adc-6cb8-4d9d-943c-f4a2c97ce4b1.png">

However, I think because [image titles are rendered using the Rails `humanize` method](https://github.com/design-history/design-history/blob/0db375fb805122258486a3683ee8ab3168b90446/app/helpers/application_helper.rb#L31), it messes up with the capitalisation, which isn't ideal:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/23801/217519212-590912fa-1bdb-4f1d-8038-95fbca31f9c2.png">

**Comment by tvararu** [comment]
Improved in:

- https://github.com/design-history/design-history/pull/229
- https://github.com/design-history/design-history/pull/228

More to do still.

**Comment by tvararu** [comment]
Closing this as though there's still more to do on screenshots, titles + alt text + captions are editable, so this particular issue is addressed.
