### ISSUE TITLE
It should be possible to add screenshots when creating a post

### ISSUE THREAD

**Issue by benilovj** [design-history/design-history#193]
When importing an existing design history, I wanted to attach screenshots immediately when creating the post:

* this is currently not possible – you have to save the draft post first, and then the widget to upload screenshots appears.
* there's no guidance/copy to tell the user that they have to save first – it was quite confusing until I realised what was going on.

**Comment by tvararu** [comment]
There's a technical reason for this: images that are uploaded must be attached to a post. If the post doesn't yet exist, there's nothing to attach to. The ways I can think of around this but involve creating a "hidden draft" post and performing some sort of periodic cleaning to ensure that unused ones are discarded.

Importing existing design histories should be more elegantly served by a more automated import process, so I don't think we should focus the design on the manual import use-case.

I think we could simplify the "New post" page further. We can ask for just the Title, which creates a draft post and takes you onto the full fledged "Edit post" page. This will also auto-generate a slug immediately.

This should address the confusing first-time user experience, and minimise the time users spend in the simpler "New post" form.
