### ISSUE TITLE
Order of pages on home page

### ISSUE THREAD

**Issue by paulrobertlloyd** [design-history/design-history#230]
No idea how pages are ordered, but doesn’t seem to be alphabetical or date based…

<img width="660" alt="Screenshot 2023-03-07 at 16 45 47" src="https://user-images.githubusercontent.com/813383/223491218-508c8687-97b3-4608-9712-c2a330940973.png">

**Comment by tvararu** [comment]
@vladh oh right! I thought it was March 2023 in the screenshot so that wasn't working for whatever reason...

@paulrobertlloyd do you think that published at date isn't sufficient in this case?
