### ISSUE TITLE
Not possible to preview a draft post

### ISSUE THREAD

**Issue by paulrobertlloyd** [design-history/design-history#234]
Have to publish a post to see what it will look like.

**Comment by tvararu** [comment]
We have a design for this: it's going to be another tab in the Post edit page. Write / Screenshots / Preview.

**Comment by tvararu** [comment]
@paulrobertlloyd we shipped some functionality for this in https://github.com/design-history/design-history/pull/304

It does enable previewing a draft post. It isn't perfect, as you can't easily preview changes to a published post (previewing requires saving). But it helps a lot in the drafting phase.

Closing this for now as resolved.
