### ISSUE TITLE
Breadcrumb missing last item

### ISSUE THREAD

**Issue by paulrobertlloyd** [design-history/design-history#317]
The last item in the breadcrumb is missing, leading the chevron to be misaligned:

<img width="360" alt="Screenshot 2023-05-22 at 15 56 54" src="https://github.com/design-history/design-history/assets/813383/6f3bbba4-eb4f-4f36-b4a2-8b163126ed43">

**Comment by tvararu** [comment]
Thanks @paulrobertlloyd! Fix coming up.
